### ISSUE TITLE
Unable to download covariance_joint

### ISSUE THREAD

**Issue by montenegrina** [Joker-Jerome/UTMOST#14]
Hello,

I was able to download other data mentioned in the tutorial but not this one. This is what I get when I try to download it:

wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies  /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA" -O covariance_joint.zip && rm -rf /tmp/cookies.txt
--2020-11-16 15:32:26--  https://drive.google.com/uc?export=download&confirm=IK4q&id=1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA
Resolving drive.google.com (drive.google.com)... 172.217.4.46, 2607:f8b0:4009:804::200e
Connecting to drive.google.com (drive.google.com)|172.217.4.46|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-14-34-docs.googleusercontent.com/docs/securesc/b6mh1vndia29l04vn76ofn4n0rafeqd9/uf32q6regjmuc8p6h95883la41ko9ual/1605562275000/03714402701562313767/17819618574684609298Z/1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA?e=download [following]
--2020-11-16 15:32:26--  https://doc-14-34-docs.googleusercontent.com/docs/securesc/b6mh1vndia29l04vn76ofn4n0rafeqd9/uf32q6regjmuc8p6h95883la41ko9ual/1605562275000/03714402701562313767/17819618574684609298Z/1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA?e=download
Resolving doc-14-34-docs.googleusercontent.com (doc-14-34-docs.googleusercontent.com)... 172.217.5.1, 2607:f8b0:4009:807::2001
Connecting to doc-14-34-docs.googleusercontent.com (doc-14-34-docs.googleusercontent.com)|172.217.5.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://docs.google.com/nonceSigner?nonce=c1em1i42e8h44&continue=https://doc-14-34-docs.googleusercontent.com/docs/securesc/b6mh1vndia29l04vn76ofn4n0rafeqd9/uf32q6regjmuc8p6h95883la41ko9ual/1605562275000/03714402701562313767/17819618574684609298Z/1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA?e%3Ddownload&hash=gccifgv4mq1fsotba5k64bn4gi1ntl31 [following]
--2020-11-16 15:32:26--  https://docs.google.com/nonceSigner?nonce=c1em1i42e8h44&continue=https://doc-14-34-docs.googleusercontent.com/docs/securesc/b6mh1vndia29l04vn76ofn4n0rafeqd9/uf32q6regjmuc8p6h95883la41ko9ual/1605562275000/03714402701562313767/17819618574684609298Z/1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA?e%3Ddownload&hash=gccifgv4mq1fsotba5k64bn4gi1ntl31
Resolving docs.google.com (docs.google.com)... 172.217.4.206, 2607:f8b0:4009:806::200e
Connecting to docs.google.com (docs.google.com)|172.217.4.206|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://doc-14-34-docs.googleusercontent.com/docs/securesc/b6mh1vndia29l04vn76ofn4n0rafeqd9/uf32q6regjmuc8p6h95883la41ko9ual/1605562275000/03714402701562313767/17819618574684609298Z/1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA?e=download&nonce=c1em1i42e8h44&user=17819618574684609298Z&hash=j391lcurg8526iqdf83591ov22714lqh [following]
--2020-11-16 15:32:26--  https://doc-14-34-docs.googleusercontent.com/docs/securesc/b6mh1vndia29l04vn76ofn4n0rafeqd9/uf32q6regjmuc8p6h95883la41ko9ual/1605562275000/03714402701562313767/17819618574684609298Z/1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA?e=download&nonce=c1em1i42e8h44&user=17819618574684609298Z&hash=j391lcurg8526iqdf83591ov22714lqh
Connecting to doc-14-34-docs.googleusercontent.com (doc-14-34-docs.googleusercontent.com)|172.217.5.1|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-11-16 15:32:27 ERROR 403: Forbidden.

Please advise,
Ana

**Comment by yiminghu** [comment]
could you try this link and see if you can directly download this file to your local disk? https://drive.google.com/uc?export=download&id=1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA

**Comment by montenegrina** [comment]
Thank you so much, the download worked perfectly!

**Comment by Joker-Jerome** [comment]
Awesome! Thanks Yiming.
