### ISSUE TITLE
unable to complete the download of pre-calculate covariance matrices

### ISSUE THREAD

**Issue by lea1010** [Joker-Jerome/UTMOST#15]
Hi.

I would like to use the pre-computed covariance matrices for single-tissue/joint test but I am unable to download it following the commands on README:

wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies  /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Kh3lHyTioKIXqCsREmsAyC-dS49KVO9G' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Kh3lHyTioKIXqCsREmsAyC-dS49KVO9G" -O covariance_tissue.tar.gz && rm -rf /tmp/cookies.txt

The download gets interrupted with the following message from the google drive:

HTTP request sent, awaiting response... 403 Forbidden
2020-11-20 11:16:43 ERROR 403: Forbidden.
 
How may I solve this issue?Thanks in advance!

Ming Wai

**Comment by Joker-Jerome** [comment]
Hi Ming,

If you go to 'https://drive.google.com/uc?export=download&id=1Kh3lHyTioKIXqCsREmsAyC-dS49KVO9G' directly. Would you be able to download the file?

Thanks,
Jerome

**Comment by lea1010** [comment]
Yes, I am able to download it now, 
Thanks a lot!
