### ISSUE TITLE
How to interpretation the output of Conditional Analysis

### ISSUE THREAD

**Issue by shengzheBian** [Joker-Jerome/UTMOST#20]
Hello，
     I have run the conditional analysis according to the document (the command is as follows)。
     Now I get a result file “results.csv”，but how to interpretation these？ I want to know whether the two genes are independent 。
     Thank you！

part of result file：
![图片](https://user-images.githubusercontent.com/66250284/116739584-6c74b880-aa26-11eb-8b93-0a79558f5d61.png)

my command：
UTMOST_path=/home/lsy-bianshengzhe/software/UTMOST/UTMOST/
python2 conditional_test_geneset.py \
--utmost_dir $UTMOST_path \
--weight_db $UTMOST_path/sample_data/weight_db_GTEx/ \
--input_folder $UTMOST_path/sample_data/dosage/ \
--gwas_str gwas \
--gwas_folder sample_data/GWAS/ \
--gwas_file_pattern SNP_gwas_mc_merge_nogc.tbl.uniq \
--snp_column SNP \
--effect_allele_column A1 \
--non_effect_allele_column A2 \
--beta_column b \
--se_column se \
--pvalue_column p \
--chr_idx 3 \
--gene_list  AADAC,AADACL2 \
--output_dir results_condition_2/

**Comment by Joker-Jerome** [comment]
Hi Shengzhe,

This conditional analysis can be used when you have multiple neighboring genes associated with the trait and you want to figure out which one is the most important contributor. In your case, you want to test which one is more important, AADAC or AADACL2. You can think of it as a multiple regression conceptually. Therefore, the final results will tell you which gene is more significant in terms of the test.

Thanks!

**Comment by shengzheBian** [comment]
Ok, It‘s very kind of you, thank you !

**Comment by Joker-Jerome** [comment]
You are welcome!
