### ISSUE TITLE
Does UTMOST include the GTEx eqtl GWAS summary statistics files which can be used for MR analysis

### ISSUE THREAD

**Issue by shengzheBian** [Joker-Jerome/UTMOST#21]
Hello,
     I have run a complete analysis successfully by UTMOST, and found some significant genes in some tissues. 
     Next, I want to perform a Mendelian randomization to explore the causal relatlionship between gene expression and outcome.
     Does UTMOST include the GTEx eqtl GWAS summary statistics files of tissues, which can be used for MR analysis directly? Or I have to get them from GTEX website?
     Thanks!

**Comment by Joker-Jerome** [comment]
Hi I don't think we support this function for now. Maybe you have to get it from GTEx portal.
