### ISSUE TITLE
empty in sample_data>covariance_joint.

### ISSUE THREAD

**Issue by beibeixiaomu** [Joker-Jerome/UTMOST#22]
@Joker-Jerome @yiminghu 
Hello
The following URL is empty: https://drive.google.com/drive/folders/11GwG8P-SqADvsf5izlV0Oy7k60VW1G10. 
I can not download anything in sample_data>covariance_joint. Is it normal or something missing?
Looking forward to your reply.
Thank you so much.

**Comment by Joker-Jerome** [comment]
Hi, 

Did you try running: 
3.2 Download pre-calculate covariance matrices for single-tissue/joint test (large file 28GB for zipped file, 45GB after unzipping)
$ cd sample_data
$ wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies  /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Kh3lHyTioKIXqCsREmsAyC-dS49KVO9G' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Kh3lHyTioKIXqCsREmsAyC-dS49KVO9G" -O covariance_tissue.tar.gz && rm -rf /tmp/cookies.txt
$ wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies  /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1tqIW5Ms8p1StX7WXXWVa4TGKb5q58TPA" -O covariance_joint.zip && rm -rf /tmp/cookies.txt
$ tar -zxvf covariance_tissue.tar.gz
$ unzip covariance_joint.zip

**Comment by beibeixiaomu** [comment]
@Joker-Jerome 
Thank you so much for your reply.
I have tried running the codes above. But maybe there is something wrong with VPN. 

### 
(UTMOST) gma15@bio1-2288H-V5:~/UTMOST/sample_data$ wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Kh3lHyTioKIXqCsREmsAyC-dS49KVO9G' -O- | sed -rn 's/.confirm=([0-9A-Za-z_]+)./\1\n/p')&id=1Kh3lHyTioKIXqCsREmsAyC-dS49KVO9G" -O covariance_tissue.tar.gz && rm -rf /tmp/cookies.txt

--2021-05-27 12:41:18--  https://drive.google.com/uc?export=download&confirm=&id=1Kh3lHyTioKIXqCsREmsAyC-dS49KVO9G
Resolving drive.google.com (drive.google.com)... 154.83.15.45, 2001::4a75:b2ad
Connecting to drive.google.com (drive.google.com)|154.83.15.45|:443... failed: Connection timed out.
Connecting to drive.google.com (drive.google.com)|2001::4a75:b2ad|:443... failed: Network is unreachable.
### 

So I am trying downloading the data from Google Drive. Or is there any other method?
Thanks.

**Comment by beibeixiaomu** [comment]
@Joker-Jerome 
Thank you so much.
Something wrong with my operating.
Now, it has been solved.
Sincerely

**Comment by Joker-Jerome** [comment]
@beibeixiaomu That's great. I was thinking of uploading the files to other platforms to solve this issue. Glad to help!
