### ISSUE TITLE
48 Tissue GTEx V7 pre-calculated covariance matrices

### ISSUE THREAD

**Issue by udube** [Joker-Jerome/UTMOST#4]
Thank you for sharing your software and providing the pre-calculated covariance matrices for 44 GTEx tissues. 

Will you also be releasing pre-calculated covariance matrices for the 48 GTEx tissues available in the v7 release? Use of this larger reference panel has been demonstrated to improve results (http://gusevlab.org/projects/fusion/gtex.html).

**Comment by Joker-Jerome** [comment]
Thanks for your great advice! Currently we only have imputation models built on 44 GTEx tissues.

**Comment by tangchao7498** [comment]
If I don't want to use GTEx as reference panel, how can I get the transcriptome model (a.k.a as 'weight DB files') of my dataset?

**Comment by Joker-Jerome** [comment]
Hi Chao,

https://github.com/yiminghu/CTIMP. Here is the repo.

**Comment by tangchao7498** [comment]
Hi Jerome,
Thank you very much for your reply! And I get a new problem when I used my imputation model to predict gene expression. 

`python ./single_tissue_association_test.py --model_db_path ~/Mono2.db --covariance ~/Mono_allCovariances.txt --gwas_folder /mnt/raid61/Personal_data/tangchao/QTL/document/GWAS_Summary_Statistic --gwas_file_pattern Ankylosing_spondylitis_IGAS-Cortes_2013_NatGen_Immunochip.txt.gz --snp_column RSid --effect_allele_column Eff_allele --non_effect_allele_column Other_allele --beta_column beta --pvalue_column pval --output_file /mnt/data1/tangchao/QTL/UTMOST/UTMOST/SingleTissue/Mono_Ankylosing_spondylitis_IGAS-Cortes_2013_NatGen_Immunochip.csv`

INFO - Processing GWAS command line parameters
INFO - Building beta for Ankylosing_spondylitis_IGAS-Cortes_2013_NatGen_Immunochip.txt.gz and /home/tangchao/Mono2.db
INFO - Reading input gwas from source
INFO - Processing input gwas
WARNING - Some GWAS snp zscores are not finite.
INFO - Successfully parsed input gwas in 40.4097158909 seconds
INFO - Started metaxcan association
INFO - Loading model from: /home/tangchao/Mono2.db
INFO - Loading covariance data from: /home/tangchao/Mono_allCovariances.txt
/mnt/raid61/Personal_data/tangchao/QTL/document/UTMOST/UTMOST/metax/MatrixManager.py:6: FutureWarning: read_table is deprecated, use read_csv instead.
  d = pandas.read_table(path, sep="\s+")
ERROR - Invalid input format: Snp Matrix Entries for genes must be contiguous but Y_RNA was found in two different places

Could anyone advice on this? Really appreciate!!

**Comment by Joker-Jerome** [comment]
Update: we will be working on updating the covariance matrices and imputation models.

**Comment by Joker-Jerome** [comment]
Hi Chao, could you tell me how you build the imputation models? Thanks!

**Comment by udube** [comment]
Updating to GTEx v7 or the recently released v8?

**Comment by Joker-Jerome** [comment]
We will go directly to v8 I think :)
