### ISSUE TITLE
No GWAS files found on ./sample_data/GWAS with pattern SNP_gwas_mc_merge_nogc.tbl.uniq

### ISSUE THREAD

**Issue by fjy-njmu** [Joker-Jerome/UTMOST#6]
Hi
I was interested in multi-tissue TWAS and I wanted to learn something about UTMOST. I had downloaded all the sample data. However, when I was running single tissue association test for 44 tissues, I always met a error: ERROR - No GWAS files found on ./sample_data/GWAS with pattern SNP_gwas_mc_merge_nogc.tbl.uniq. As just for test, I just chose a tissue.
Here is my code

python ./single_tissue_association_test.py \
--model_db_path ./sample_data/weight_db_GTEx/Adipose_Subcutaneous.db \
--covariance ./sample_data/covariance_tissue/Adipose_Subcutaneous.txt.gz \
--gwas_folder ./sample_data/GWAS \
--gwas_file_pattern ./SNP_gwas_mc_merge_nogc.tbl.uniq \
--snp_column SNP \
--effect_allele_column A1 \
--non_effect_allele_column A2 \
--beta_column b \
--pvalue_column p \
--output_file ./UTMOST_results/Adipose_Subcutaneous.csv

I had tried several times and I did not change anything downloaded. 
Could anyone advice on this? Really appreciate!!
Joy

**Comment by jialeyang0104** [comment]
Met the same problem. How did you solve it? Looking forward to your response.
